// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/filinvadim/bigchaindb-go/models"
)

// GetAssetsReader is a Reader for the GetAssets structure.
type GetAssetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAssetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAssetsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /assets] GetAssets", response, response.Code())
	}
}

// NewGetAssetsOK creates a GetAssetsOK with default headers values
func NewGetAssetsOK() *GetAssetsOK {
	return &GetAssetsOK{}
}

/*
GetAssetsOK describes a response with status code 200, with default header values.

Successful response with a list of matching assets
*/
type GetAssetsOK struct {
	Payload []*models.Asset
}

// IsSuccess returns true when this get assets o k response has a 2xx status code
func (o *GetAssetsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get assets o k response has a 3xx status code
func (o *GetAssetsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets o k response has a 4xx status code
func (o *GetAssetsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get assets o k response has a 5xx status code
func (o *GetAssetsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets o k response a status code equal to that given
func (o *GetAssetsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get assets o k response
func (o *GetAssetsOK) Code() int {
	return 200
}

func (o *GetAssetsOK) Error() string {
	return fmt.Sprintf("[GET /assets][%d] getAssetsOK  %+v", 200, o.Payload)
}

func (o *GetAssetsOK) String() string {
	return fmt.Sprintf("[GET /assets][%d] getAssetsOK  %+v", 200, o.Payload)
}

func (o *GetAssetsOK) GetPayload() []*models.Asset {
	return o.Payload
}

func (o *GetAssetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssetsBadRequest creates a GetAssetsBadRequest with default headers values
func NewGetAssetsBadRequest() *GetAssetsBadRequest {
	return &GetAssetsBadRequest{}
}

/*
GetAssetsBadRequest describes a response with status code 400, with default header values.

Bad Request - The query was not executed successfully
*/
type GetAssetsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get assets bad request response has a 2xx status code
func (o *GetAssetsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get assets bad request response has a 3xx status code
func (o *GetAssetsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get assets bad request response has a 4xx status code
func (o *GetAssetsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get assets bad request response has a 5xx status code
func (o *GetAssetsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get assets bad request response a status code equal to that given
func (o *GetAssetsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get assets bad request response
func (o *GetAssetsBadRequest) Code() int {
	return 400
}

func (o *GetAssetsBadRequest) Error() string {
	return fmt.Sprintf("[GET /assets][%d] getAssetsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAssetsBadRequest) String() string {
	return fmt.Sprintf("[GET /assets][%d] getAssetsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAssetsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAssetsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
