// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/filinvadim/bigchaindb-go/models"
)

// GetMetadataReader is a Reader for the GetMetadata structure.
type GetMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMetadataBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /metadata] GetMetadata", response, response.Code())
	}
}

// NewGetMetadataOK creates a GetMetadataOK with default headers values
func NewGetMetadataOK() *GetMetadataOK {
	return &GetMetadataOK{}
}

/*
GetMetadataOK describes a response with status code 200, with default header values.

Successful response with a list of matching metadata objects
*/
type GetMetadataOK struct {
	Payload []models.Metadata
}

// IsSuccess returns true when this get metadata o k response has a 2xx status code
func (o *GetMetadataOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get metadata o k response has a 3xx status code
func (o *GetMetadataOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get metadata o k response has a 4xx status code
func (o *GetMetadataOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get metadata o k response has a 5xx status code
func (o *GetMetadataOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get metadata o k response a status code equal to that given
func (o *GetMetadataOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get metadata o k response
func (o *GetMetadataOK) Code() int {
	return 200
}

func (o *GetMetadataOK) Error() string {
	return fmt.Sprintf("[GET /metadata][%d] getMetadataOK  %+v", 200, o.Payload)
}

func (o *GetMetadataOK) String() string {
	return fmt.Sprintf("[GET /metadata][%d] getMetadataOK  %+v", 200, o.Payload)
}

func (o *GetMetadataOK) GetPayload() []models.Metadata {
	return o.Payload
}

func (o *GetMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMetadataBadRequest creates a GetMetadataBadRequest with default headers values
func NewGetMetadataBadRequest() *GetMetadataBadRequest {
	return &GetMetadataBadRequest{}
}

/*
GetMetadataBadRequest describes a response with status code 400, with default header values.

Bad Request - The query was not executed successfully
*/
type GetMetadataBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get metadata bad request response has a 2xx status code
func (o *GetMetadataBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get metadata bad request response has a 3xx status code
func (o *GetMetadataBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get metadata bad request response has a 4xx status code
func (o *GetMetadataBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get metadata bad request response has a 5xx status code
func (o *GetMetadataBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get metadata bad request response a status code equal to that given
func (o *GetMetadataBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get metadata bad request response
func (o *GetMetadataBadRequest) Code() int {
	return 400
}

func (o *GetMetadataBadRequest) Error() string {
	return fmt.Sprintf("[GET /metadata][%d] getMetadataBadRequest  %+v", 400, o.Payload)
}

func (o *GetMetadataBadRequest) String() string {
	return fmt.Sprintf("[GET /metadata][%d] getMetadataBadRequest  %+v", 400, o.Payload)
}

func (o *GetMetadataBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetMetadataBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
