// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAssetsParams creates a new GetAssetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetsParams() *GetAssetsParams {
	return &GetAssetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetsParamsWithTimeout creates a new GetAssetsParams object
// with the ability to set a timeout on a request.
func NewGetAssetsParamsWithTimeout(timeout time.Duration) *GetAssetsParams {
	return &GetAssetsParams{
		timeout: timeout,
	}
}

// NewGetAssetsParamsWithContext creates a new GetAssetsParams object
// with the ability to set a context for a request.
func NewGetAssetsParamsWithContext(ctx context.Context) *GetAssetsParams {
	return &GetAssetsParams{
		Context: ctx,
	}
}

// NewGetAssetsParamsWithHTTPClient creates a new GetAssetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetsParamsWithHTTPClient(client *http.Client) *GetAssetsParams {
	return &GetAssetsParams{
		HTTPClient: client,
	}
}

/*
GetAssetsParams contains all the parameters to send to the API endpoint

	for the get assets operation.

	Typically these are written to a http.Request.
*/
type GetAssetsParams struct {

	/* Limit.

	   Limit the number of returned assets
	*/
	Limit *int64

	/* Search.

	   Text search string to query
	*/
	Search string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get assets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsParams) WithDefaults() *GetAssetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get assets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get assets params
func (o *GetAssetsParams) WithTimeout(timeout time.Duration) *GetAssetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get assets params
func (o *GetAssetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get assets params
func (o *GetAssetsParams) WithContext(ctx context.Context) *GetAssetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get assets params
func (o *GetAssetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get assets params
func (o *GetAssetsParams) WithHTTPClient(client *http.Client) *GetAssetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get assets params
func (o *GetAssetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get assets params
func (o *GetAssetsParams) WithLimit(limit *int64) *GetAssetsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get assets params
func (o *GetAssetsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSearch adds the search to the get assets params
func (o *GetAssetsParams) WithSearch(search string) *GetAssetsParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get assets params
func (o *GetAssetsParams) SetSearch(search string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// query param search
	qrSearch := o.Search
	qSearch := qrSearch
	if qSearch != "" {

		if err := r.SetQueryParam("search", qSearch); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
