// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/filinvadim/bigchaindb-go/models"
)

// GetBlocksBlockHeightReader is a Reader for the GetBlocksBlockHeight structure.
type GetBlocksBlockHeightReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBlocksBlockHeightReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBlocksBlockHeightOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBlocksBlockHeightBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBlocksBlockHeightNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /blocks/{block_height}] GetBlocksBlockHeight", response, response.Code())
	}
}

// NewGetBlocksBlockHeightOK creates a GetBlocksBlockHeightOK with default headers values
func NewGetBlocksBlockHeightOK() *GetBlocksBlockHeightOK {
	return &GetBlocksBlockHeightOK{}
}

/*
GetBlocksBlockHeightOK describes a response with status code 200, with default header values.

Successful response with the block details
*/
type GetBlocksBlockHeightOK struct {
	Payload *models.Block
}

// IsSuccess returns true when this get blocks block height o k response has a 2xx status code
func (o *GetBlocksBlockHeightOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get blocks block height o k response has a 3xx status code
func (o *GetBlocksBlockHeightOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blocks block height o k response has a 4xx status code
func (o *GetBlocksBlockHeightOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get blocks block height o k response has a 5xx status code
func (o *GetBlocksBlockHeightOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get blocks block height o k response a status code equal to that given
func (o *GetBlocksBlockHeightOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get blocks block height o k response
func (o *GetBlocksBlockHeightOK) Code() int {
	return 200
}

func (o *GetBlocksBlockHeightOK) Error() string {
	return fmt.Sprintf("[GET /blocks/{block_height}][%d] getBlocksBlockHeightOK  %+v", 200, o.Payload)
}

func (o *GetBlocksBlockHeightOK) String() string {
	return fmt.Sprintf("[GET /blocks/{block_height}][%d] getBlocksBlockHeightOK  %+v", 200, o.Payload)
}

func (o *GetBlocksBlockHeightOK) GetPayload() *models.Block {
	return o.Payload
}

func (o *GetBlocksBlockHeightOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Block)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBlocksBlockHeightBadRequest creates a GetBlocksBlockHeightBadRequest with default headers values
func NewGetBlocksBlockHeightBadRequest() *GetBlocksBlockHeightBadRequest {
	return &GetBlocksBlockHeightBadRequest{}
}

/*
GetBlocksBlockHeightBadRequest describes a response with status code 400, with default header values.

Bad Request - The request wasn’t understood by the server
*/
type GetBlocksBlockHeightBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get blocks block height bad request response has a 2xx status code
func (o *GetBlocksBlockHeightBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get blocks block height bad request response has a 3xx status code
func (o *GetBlocksBlockHeightBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blocks block height bad request response has a 4xx status code
func (o *GetBlocksBlockHeightBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get blocks block height bad request response has a 5xx status code
func (o *GetBlocksBlockHeightBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get blocks block height bad request response a status code equal to that given
func (o *GetBlocksBlockHeightBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get blocks block height bad request response
func (o *GetBlocksBlockHeightBadRequest) Code() int {
	return 400
}

func (o *GetBlocksBlockHeightBadRequest) Error() string {
	return fmt.Sprintf("[GET /blocks/{block_height}][%d] getBlocksBlockHeightBadRequest  %+v", 400, o.Payload)
}

func (o *GetBlocksBlockHeightBadRequest) String() string {
	return fmt.Sprintf("[GET /blocks/{block_height}][%d] getBlocksBlockHeightBadRequest  %+v", 400, o.Payload)
}

func (o *GetBlocksBlockHeightBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBlocksBlockHeightBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBlocksBlockHeightNotFound creates a GetBlocksBlockHeightNotFound with default headers values
func NewGetBlocksBlockHeightNotFound() *GetBlocksBlockHeightNotFound {
	return &GetBlocksBlockHeightNotFound{}
}

/*
GetBlocksBlockHeightNotFound describes a response with status code 404, with default header values.

Not Found - A block with that block height was not found
*/
type GetBlocksBlockHeightNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get blocks block height not found response has a 2xx status code
func (o *GetBlocksBlockHeightNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get blocks block height not found response has a 3xx status code
func (o *GetBlocksBlockHeightNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blocks block height not found response has a 4xx status code
func (o *GetBlocksBlockHeightNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get blocks block height not found response has a 5xx status code
func (o *GetBlocksBlockHeightNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get blocks block height not found response a status code equal to that given
func (o *GetBlocksBlockHeightNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get blocks block height not found response
func (o *GetBlocksBlockHeightNotFound) Code() int {
	return 404
}

func (o *GetBlocksBlockHeightNotFound) Error() string {
	return fmt.Sprintf("[GET /blocks/{block_height}][%d] getBlocksBlockHeightNotFound  %+v", 404, o.Payload)
}

func (o *GetBlocksBlockHeightNotFound) String() string {
	return fmt.Sprintf("[GET /blocks/{block_height}][%d] getBlocksBlockHeightNotFound  %+v", 404, o.Payload)
}

func (o *GetBlocksBlockHeightNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBlocksBlockHeightNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
