// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBlocksBlockHeightParams creates a new GetBlocksBlockHeightParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBlocksBlockHeightParams() *GetBlocksBlockHeightParams {
	return &GetBlocksBlockHeightParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBlocksBlockHeightParamsWithTimeout creates a new GetBlocksBlockHeightParams object
// with the ability to set a timeout on a request.
func NewGetBlocksBlockHeightParamsWithTimeout(timeout time.Duration) *GetBlocksBlockHeightParams {
	return &GetBlocksBlockHeightParams{
		timeout: timeout,
	}
}

// NewGetBlocksBlockHeightParamsWithContext creates a new GetBlocksBlockHeightParams object
// with the ability to set a context for a request.
func NewGetBlocksBlockHeightParamsWithContext(ctx context.Context) *GetBlocksBlockHeightParams {
	return &GetBlocksBlockHeightParams{
		Context: ctx,
	}
}

// NewGetBlocksBlockHeightParamsWithHTTPClient creates a new GetBlocksBlockHeightParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBlocksBlockHeightParamsWithHTTPClient(client *http.Client) *GetBlocksBlockHeightParams {
	return &GetBlocksBlockHeightParams{
		HTTPClient: client,
	}
}

/*
GetBlocksBlockHeightParams contains all the parameters to send to the API endpoint

	for the get blocks block height operation.

	Typically these are written to a http.Request.
*/
type GetBlocksBlockHeightParams struct {

	/* BlockHeight.

	   Block height
	*/
	BlockHeight int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get blocks block height params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBlocksBlockHeightParams) WithDefaults() *GetBlocksBlockHeightParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get blocks block height params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBlocksBlockHeightParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get blocks block height params
func (o *GetBlocksBlockHeightParams) WithTimeout(timeout time.Duration) *GetBlocksBlockHeightParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get blocks block height params
func (o *GetBlocksBlockHeightParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get blocks block height params
func (o *GetBlocksBlockHeightParams) WithContext(ctx context.Context) *GetBlocksBlockHeightParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get blocks block height params
func (o *GetBlocksBlockHeightParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get blocks block height params
func (o *GetBlocksBlockHeightParams) WithHTTPClient(client *http.Client) *GetBlocksBlockHeightParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get blocks block height params
func (o *GetBlocksBlockHeightParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBlockHeight adds the blockHeight to the get blocks block height params
func (o *GetBlocksBlockHeightParams) WithBlockHeight(blockHeight int64) *GetBlocksBlockHeightParams {
	o.SetBlockHeight(blockHeight)
	return o
}

// SetBlockHeight adds the blockHeight to the get blocks block height params
func (o *GetBlocksBlockHeightParams) SetBlockHeight(blockHeight int64) {
	o.BlockHeight = blockHeight
}

// WriteToRequest writes these params to a swagger request
func (o *GetBlocksBlockHeightParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param block_height
	if err := r.SetPathParam("block_height", swag.FormatInt64(o.BlockHeight)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
