// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ValidTransactionResponse valid transaction response
//
// swagger:model ValidTransactionResponse
type ValidTransactionResponse struct {

	// asset id
	AssetID string `json:"asset_id,omitempty"`

	// height
	Height int64 `json:"height,omitempty"`

	// transaction id
	TransactionID string `json:"transaction_id,omitempty"`
}

// Validate validates this valid transaction response
func (m *ValidTransactionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this valid transaction response based on context it is used
func (m *ValidTransactionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidTransactionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidTransactionResponse) UnmarshalBinary(b []byte) error {
	var res ValidTransactionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
